Dim oSelOcc As ComponentOccurrence
Dim strSelectPath As String = ""
Dim bFlag As Boolean = False

Select Case MsgBox("Do you want to select an occurrence (Yes) or use standard file paths (No)", MsgBoxStyle.YesNoCancel, "caption")
	Case MsgBoxResult.Yes
		oSelOcc = ThisApplication.CommandManager.Pick(16643,"Select Occurrence To Hide") '16643 = kAssemblyLeafOccurrenceFilter
		strSelectPath = oSelOcc.ReferencedDocumentDescriptor.FullDocumentName
		bFlag = True
	Case MsgBoxResult.Cancel
		Exit Sub
	Case MsgBoxResult.No
		bFlag = False
End Select

Dim oDoc As AssemblyDocument = ThisApplication.ActiveDocument
Dim oCompDef As AssemblyComponentDefinition = oDoc.ComponentDefinition
Dim oLeafOccs As ComponentOccurrencesEnumerator = oCompDef.Occurrences.AllLeafOccurrences
Dim oOcc As ComponentOccurrence

Dim strCustomPath As String = ""
Dim strPath1 As String = "C:\Workspace\Libraries\Content Centre Files\en-US\"
Dim strPath2 As String = "C:\Workspace\Libraries\..."
Dim strPath3 As String = "C:\Workspace\Libraries\..."

Dim errorstep As String = "1"

' Create a new transaction to enable single click undo for all items
'Dim oTransMan As TransactionManager = ThisApplication.Tra
'Dim oTrans As Transaction

' Iterate through all Leaf occurrences and hide matching files
Try
	For Each oOcc In oLeafOccs
		If TypeOf oOcc.Definition Is VirtualComponentDefinition Then Continue For
		errorstep = "a"
		strOcc = oOcc.ReferencedDocumentDescriptor.FullDocumentName
		errorstep = "2"

		' Test if selection option is used then run that if it is
		If bFlag = True Then
			If strOcc.Contains(strSelectPath) Then
				oOcc.Visible = False
			End If
			Continue For
		End If
		
		' This is the standard  path option
		If strOcc.Contains(strPath1) Then
			errorstep = "3 - " & strOcc
			oOcc.Visible = False
		ElseIf strOcc.Contains(strPath2) Then
			errorstep = "4 - " & strOcc
			oOcc.Visible = False
		Else If strOcc.Contains(strPath3) Then
			errorstep = "5 - " & strOcc
			oOcc.Visible = False
		End If
		errorstep = "6 - " & strOcc & oOcc.DefinitionDocumentType
	Next

Catch Ex As Exception
MessageBox.Show(ex.Message & " - " & errorstep)
End Try

